### PR TITLE
Add fps setting and equalize animation speed

### PR DESCRIPTION
**Pull request by Silarn**
The speed of the snowflakes varies drastically between one machine/browser and the next, due to rendering speed capability. This code adds a frames per second config option and adjusts the speed of each snowflake to move the defined number of pixels at that framerate. (So if the speed is 1 and the fps is 30, each 30th of a second the snowflake will fall one pixel and make one full x-step in the 'wiggle' cosine function.)

### CODE REVIEW

**Comment by Skaronator** [comment]
any update on this pullrequest?

**Comment by Silarn** [comment]
I believe the recent pull request that uses css transforms accomplishes the same goal, unless you're trying to support IE 9 or earlier. Mind you Microsoft has officially stated they're dropping support for IE prior to 11 in 2016.

**Comment by loktar00** [comment]
@Silarn is correct, closing this since it is no longer an issue.

**Comment by Skaronator** [comment]
alright, thanks for the quick response from both!

**Pull request closed without merging**
